
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider :virtualbox do |vb, override|
      vb.name = "labdocker"
      vb.memory = 2048
      vb.cpus = 2
    end
    config.vm.network "forwarded_port", guest: 80, host: 5060, host_ip: "127.0.0.1", id: "mywordpress"
   
    config.vm.provision :shell, :path => "scriptDocker.sh"
    config.vm.provision :shell, :path => "scriptWordpress.sh", run:"always"
  end
  