
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |vb, override|
    vb.name = "lab3"
    vb.memory = 2048
    vb.cpus = 2
    diskFormat = "vdi"
    diskCount = 4
    (1..diskCount).each do |i|
    
      disk = "./disk" + "#{i}" + "." + diskFormat
      if !File.exist?(disk)
        vb.customize [ "createhd", "--filename", disk, "--variant", "Fixed", "--size", 350 ]
        vb.customize [ "storageattach", "lab3" ,'--storagectl', 'SATAController', '--port', i, '--device', 0, '--type', 'hdd', '--medium', disk]
      end
    end

  end
  config.vm.provision :shell, :path => "script.sh", run: "always"
end
